# version: '3.8'

services:
  genesys:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/genesys
      - ~/.cache/huggingface:/root/.cache/huggingface
    working_dir: /root/genesys
    tty: true
    stdin_open: true
    runtime: nvidia
    command: /bin/bash 