### adapted from https://github.com/InternLM/SWE-Fixer/blob/main/evaluation/code_edit.py
import json
import re
import ast
import argparse
import cydifflib
from genesys.schemas import Response
from genesys.verifiers.base_verifier import BaseVerifier


LINE_NUMBER_REGEX = re.compile(r"^\d+\s", re.MULTILINE)


def parse_json_codeblock_from_model_output(markdown_str):
    # Get everything after </think>, if it exists
    match = re.search(r"</think>(.*?)$", markdown_str, re.DOTALL)
    answer_str = match.group(1).strip() if match else markdown_str.strip()
    # Extract everything between ```json and ``` markers
    match = re.search(r"```json\s*(.*?)\s*```", answer_str, re.DOTALL)
    if match:
        return match.group(1).strip()
    else:
        return answer_str.strip()

def remove_line_numbers(content):
    return LINE_NUMBER_REGEX.sub("", content)

def remove_empty_lines(code):
    lines = code.splitlines()
    filtered_lines = [line for line in lines if line.strip() != ""]
    return "\n".join(filtered_lines)

def check_syntax(code):
    if not code.strip():
        return False
    try:
        ast.parse(code)
    except SyntaxError:
        return False
    return True

def print_unified_diff(code, prev_code):
    diff = list(cydifflib.unified_diff(prev_code.splitlines(), code.splitlines(), 
                                     fromfile='before', tofile='after', lineterm=''))
    for line in diff:
        if line.startswith('+'):
            print('\033[92m' + line + '\033[0m')  # Green for additions
        elif line.startswith('-'): 
            print('\033[91m' + line + '\033[0m')  # Red for deletions
        else:
            print(line)  # Context lines


class SweFixerVerifier(BaseVerifier):
    """
    Verifier for the SWE-Fixer dataset.
    https://github.com/InternLM/SWE-Fixer
    """

    def apply_patches(self, files_to_modify, patches):
        """
        Apply a list of code-edit patches to an iterable of files and return the
        fully-patched workspace.

        Args:
            files_to_modify (list[dict]): items from verification_info["input"]["files to be modified"]
            patches (list[dict]): items structured like verification_info["output"]["edited code"]
                                or the model's JSON output.

        Returns
        -------
        dict[str, str]
            file-path -> patched file content
        """
        file_map = {f["file"]: remove_line_numbers(f["file content"])
                    for f in files_to_modify}

        for patch in patches:
            file_path = patch["file"]
            snippet_old = remove_line_numbers(
                patch["code snippet to be modified"]
            ).rstrip()
            snippet_new = patch["edited code snippet"]

            current = file_map.get(file_path, "")
            if snippet_old and snippet_old in current:
                current = current.replace(snippet_old, snippet_new)
            elif current == "":           # brand-new file
                current = snippet_new
            file_map[file_path] = current

        return file_map


    def exctract_code_regions(self, expected_code, predicted_code, model_patches, window=3):
        """
        Extract the code regions modified by the model.
        
        Args:
            expected_code: The reference/target code
            predicted_code: The code generated by the model
            model_patches: List of dictionaries with "edited code snippet" and "code snippet to be modified"
            window: Number of extra characters to include around each modification
            
        Returns:
            Tuple of (expected_code, predicted_code) with only the modified regions
        """
        matching_regions = []  # list[(expected_start, expected_end, predicted_start, predicted_end)]
        
        for patch in model_patches:
            old_code = patch["code snippet to be modified"]
            new_code = patch["edited code snippet"]
            
            pred_start = predicted_code.find(new_code)
            if pred_start == -1:
                continue
            pred_end = pred_start + len(new_code)
            
            expected_start = expected_code.find(old_code)
            if expected_start == -1:
                # Fallback: use same position as in predicted file if possible
                expected_start = pred_start if pred_start < len(expected_code) else None
                if expected_start is None:
                    continue
            expected_end = expected_start + len(old_code)
            
            # Expand regions by window size while respecting file boundaries
            expected_start = max(0, expected_start - window)
            expected_end = min(len(expected_code), expected_end + window)
            pred_start = max(0, pred_start - window)
            pred_end = min(len(predicted_code), pred_end + window)
            
            matching_regions.append((expected_start, expected_end, pred_start, pred_end))
        
        if not matching_regions:
            return expected_code, predicted_code
        
        pred_sections = [predicted_code[start:end] for start, end, _, _ in matching_regions]
        expected_sections = [expected_code[start:end] for _, _, start, end in matching_regions]
        
        joined_pred = "\n".join(pred_sections)
        joined_expected = "\n".join(expected_sections)
        
        return joined_expected, joined_pred

    def evaluate_task_code_editing(self, verification_info, json_output):
        try:
            model_patches = json.loads(json_output)
        except Exception as e:
            return dict(score=0.0, verification_result_info={
                "failure_reason": f"Error in parsing JSON output: {e}"
            })

        try:
            original_files = verification_info["input"]["files to be modified"]
            golden_patches = verification_info["output"]["edited code"]

            # print("PATCHING GOLDEN PATCHES")
            expected_ws  = self.apply_patches(original_files, golden_patches)
            # print("PATCHING MODEL PATCHES")
            predicted_ws = self.apply_patches(original_files, model_patches)
            # predicted_ws = apply_patches(original_files, golden_patches)

            

            scores = []
            for path in expected_ws:
                expected_code  = expected_ws[path]
                predicted_code = predicted_ws.get(path, "")
                expected_code = remove_empty_lines(expected_code)
                predicted_code = remove_empty_lines(predicted_code)

                if predicted_code == expected_code:
                    scores.append(1.0)
                    continue


                syntax_ok = check_syntax(predicted_code)
                if not syntax_ok:
                    # color_print_diff(predicted_code, expected_code)
                    return dict(score=0.0, verification_result_info={
                        "failure_reason": "Syntax error"
                    })
                
                expected_code, predicted_code = self.exctract_code_regions(expected_code, predicted_code, model_patches)
                score = cydifflib.SequenceMatcher(
                    None,
                    a=predicted_code,
                    b=expected_code,
                    autojunk=False,
                ).ratio()
                scores.append(score)
                

            return dict(score=sum(scores) / len(scores), verification_result_info=dict())


        except Exception as e:
            return dict(
                score=0,
                verification_result_info={
                    "failure_reason": f"Error in evaluating task code editing: {e}"
                },
            )

    def verify(self, result: Response):
        """
        Evaluates the code patches by comparing the model's patches against golden patches.

        The score is either 0 or 1, representing whether the patches are correct.
        """

        print("Processing example: ", result["problem_id"])
        verification_info = result["verification_info"]
        json_output = parse_json_codeblock_from_model_output(result["llm_response"])

        import time
        start_time = time.time()
        ret = self.evaluate_task_code_editing(verification_info, json_output)
        end_time = time.time()
        print(f"Time taken: {end_time - start_time} seconds")
        return ret



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Verify SWE-Fixer patches')
    parser.add_argument('--file', type=str, required=True, help='Path to the input file containing patches to verify')
    args = parser.parse_args()

    to_verify = []
    with open(args.file, "r") as f:
        for line in f:
            d = json.loads(line)
            d["verification_info"] = ast.literal_eval(d["verification_info"])
            d["metadata"] = ast.literal_eval(d["metadata"])
            to_verify.append(d)
    
    verifier = SweFixerVerifier()
    for item in to_verify:
        result = verifier.verify(item)
        print(result)
