### adapted from https://github.com/InternLM/SWE-Fixer/blob/main/evaluation/code_edit.py
import json
import re
import ast
import argparse
import cydifflib
from genesys.schemas import Response
from genesys.verifiers.base_verifier import BaseVerifier


LINE_NUMBER_REGEX = re.compile(r"^\d+\s", re.MULTILINE)


def parse_json_codeblock_from_model_output(markdown_str):
    # Get everything after </think>, if it exists
    match = re.search(r"</think>(.*?)$", markdown_str, re.DOTALL)
    answer_str = match.group(1).strip() if match else markdown_str.strip()
    # Extract everything between ```json and ``` markers
    match = re.search(r"```json\s*(.*?)\s*```", answer_str, re.DOTALL)
    if match:
        return match.group(1).strip()
    else:
        return answer_str.strip()

def remove_line_numbers(content):
    return LINE_NUMBER_REGEX.sub("", content)

def remove_empty_lines(code):
    lines = code.splitlines()
    filtered_lines = [line for line in lines if line.strip() != ""]
    return "\n".join(filtered_lines)

def check_syntax(code):
    if not code.strip():
        return False
    try:
        ast.parse(code)
    except SyntaxError:
        return False
    return True

def print_unified_diff(code, prev_code):
    diff = list(cydifflib.unified_diff(prev_code.splitlines(), code.splitlines(), 
                                     fromfile='before', tofile='after', lineterm=''))
    for line in diff:
        if line.startswith('+'):
            print('\033[92m' + line + '\033[0m')  # Green for additions
        elif line.startswith('-'): 
            print('\033[91m' + line + '\033[0m')  # Red for deletions
        else:
            print(line)  # Context lines


class SweFixerVerifier(BaseVerifier):
    """
    Verifier for the SWE-Fixer dataset.
    https://github.com/InternLM/SWE-Fixer
    """

    def apply_patches(self, files_to_modify, patches):
        """
        Apply a list of code-edit patches to an iterable of files and return the
        fully-patched workspace.

        Args:
            files_to_modify (list[dict]): items from verification_info["input"]["files to be modified"]
            patches (list[dict]): items structured like verification_info["output"]["edited code"]
                                or the model's JSON output.

        Returns
        -------
        dict[str, str]
            file-path -> patched file content
        """
        file_map = {f["file"]: remove_line_numbers(f["file content"])
                    for f in files_to_modify}

        for patch in patches:
            file_path = patch["file"]
            snippet_old = remove_line_numbers(
                patch["code snippet to be modified"]
            ).rstrip()
            snippet_new = patch["edited code snippet"]

            current = file_map.get(file_path, "")
            if snippet_old and snippet_old in current:
                current = current.replace(snippet_old, snippet_new)
            elif current == "":           # brand-new file
                current = snippet_new
            file_map[file_path] = current

        return file_map


    def exctract_code_regions(self, expected_file_content, predicted_file_content, model_patches, window=3):
        """
        Extract the code regions modified by the model.
        
        Args:
            expected_file_content: The reference/target code
            predicted_file_content: The code generated by the model
            model_patches: List of dictionaries with "edited code snippet" and "code snippet to be modified"
            window: Number of extra lines to include around each modification
            
        Returns:
            Tuple of (expected_file_content, predicted_file_content) with only the modified regions
        """
        matching_regions = []  # list[(expected_start, expected_end, predicted_start, predicted_end)]
        
        expected_lines = expected_file_content.splitlines()
        predicted_lines = predicted_file_content.splitlines()
        
        for patch in model_patches:
            # breakpoint()
            old_code = patch["code snippet to be modified"]
            new_code = patch["edited code snippet"]
            # old_code = remove_empty_lines(old_code)
            # new_code = remove_empty_lines(new_code)
            
            pred_text = "\n".join(predicted_lines)
            pred_start_char = pred_text.find(new_code)
            if pred_start_char == -1:
                print(f"new_code not found in predicted file")
                continue
                
            # Find the line numbers of the edited code
            pred_start_line = pred_text.count("\n", 0, pred_start_char)
            pred_end_line = pred_start_line + new_code.count("\n") + 1
            
            # Find the line numbers where the old code appears in expected code
            expected_text = "\n".join(expected_lines)
            expected_start_char = expected_text.find(old_code)
            if expected_start_char == -1:
                print(f"old_code not found in expected file")
                # Fallback: use same line position as in predicted file if possible
                expected_start_line = pred_start_line if pred_start_line < len(expected_lines) else None
                if expected_start_line is None:
                    continue
                expected_end_line = expected_start_line + old_code.count("\n") + 1
            else:
                expected_start_line = expected_text.count("\n", 0, expected_start_char)
                expected_end_line = expected_start_line + old_code.count("\n") + 1
            
            # Expand regions by window size while respecting file boundaries
            expected_start_line = max(0, expected_start_line - window)
            expected_end_line = min(len(expected_lines), expected_end_line + window)
            pred_start_line = max(0, pred_start_line - window)
            pred_end_line = min(len(predicted_lines), pred_end_line + window)
            
            matching_regions.append((expected_start_line, expected_end_line, pred_start_line, pred_end_line))
        
        if len(matching_regions) != len(model_patches):
            return expected_file_content, predicted_file_content
        
        expected_sections = ['\n'.join(expected_lines[start:end]) for start, end, _, _ in matching_regions]
        pred_sections = ['\n'.join(predicted_lines[start:end]) for _, _, start, end in matching_regions]
        
        joined_expected = "\n".join(expected_sections)
        joined_pred = "\n".join(pred_sections)
        
        return joined_expected, joined_pred

    def evaluate_task_code_editing(self, verification_info, json_output):
        try:
            model_patches = json.loads(json_output)
        except Exception as e:
            return dict(score=0.0, verification_result_info={
                "failure_reason": f"Error in parsing JSON output: {e}"
            })

        try:
            original_files = verification_info["input"]["files to be modified"]
            golden_patches = verification_info["output"]["edited code"]

            # print("PATCHING GOLDEN PATCHES")
            expected_workspace  = self.apply_patches(original_files, golden_patches)
            # print("PATCHING MODEL PATCHES")
            predicted_workspace = self.apply_patches(original_files, model_patches)
            # predicted_ws = apply_patches(original_files, golden_patches)

            

            scores = []
            for path in expected_workspace:
                expected_file_content  = expected_workspace[path]
                predicted_file_content = predicted_workspace.get(path, "")
                # expected_file_content = remove_empty_lines(expected_file_content)
                # predicted_file_content = remove_empty_lines(predicted_file_content)

                if predicted_file_content == expected_file_content:
                    scores.append(1.0)
                    continue


                syntax_ok = check_syntax(predicted_file_content)
                if not syntax_ok:
                    # color_print_diff(predicted_code, expected_code)
                    return dict(score=0.0, verification_result_info={
                        "failure_reason": "Syntax error"
                    })
                
                expected_file_regions, predicted_file_regions = self.exctract_code_regions(expected_file_content, predicted_file_content, model_patches)
                # print left and right side by side
                # print(predicted_file_regions)
                # print("-"*100)
                # print(expected_file_regions)
                # print("="*100)
                # print line count
                # print(predicted_file_regions.count("\n"))
                # print(expected_file_regions.count("\n"))
                score = cydifflib.SequenceMatcher(
                    None,
                    a=predicted_file_regions,
                    b=expected_file_regions,
                    autojunk=False,
                ).ratio()
                scores.append(score)
                

            return dict(score=sum(scores) / len(scores), verification_result_info=dict())


        except Exception as e:
            return dict(
                score=0,
                verification_result_info={
                    "failure_reason": f"Error in evaluating task code editing: {e}"
                },
            )

    def verify(self, result: Response):
        """
        Evaluates the code patches by comparing the model's patches against golden patches.

        The score is either 0 or 1, representing whether the patches are correct.
        """

        print("Processing example: ", result["problem_id"])
        verification_info = result["verification_info"]
        json_output = parse_json_codeblock_from_model_output(result["llm_response"])

        import time
        start_time = time.time()
        ret = self.evaluate_task_code_editing(verification_info, json_output)
        end_time = time.time()
        # print(f"Time taken: {end_time - start_time} seconds")
        return ret



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Verify SWE-Fixer patches')
    parser.add_argument('--file', type=str, required=True, help='Path to the input file containing patches to verify')
    args = parser.parse_args()

    to_verify = []
    with open(args.file, "r") as f:
        for line in f:
            d = json.loads(line)
            d["verification_info"] = ast.literal_eval(d["verification_info"])
            d["metadata"] = ast.literal_eval(d["metadata"])
            to_verify.append(d)
    
    verifier = SweFixerVerifier()
    for item in to_verify:
        result = verifier.verify(item)
        print(result)
